name: Integracion Continua Node.js

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Instalar dependencias del proyecto
      run: npm install
