

version: '3.8'

services:
  # Aca coloco el servicio de la Base de datos Postgres, Osea Múltiples servicios
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: mi_base_datos
    volumes:
      - db-data:/var/lib/postgresql/data
    # Chequeo de la salud estructural (el Healthcheck)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops_user -d mi_base_datos"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops-network
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://devops_user:devops_password@db:5432/mi_base_datos
    # depends_on condicional: espera a que la Base de datos  esté saludable antes de arrancar y  evitar problemas
    depends_on:
      db:
        condition: service_healthy
    # Parámetros de fiabilidad: límites estrictos de CPU y Memoria
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - devops-network

volumes:
  db-data:

networks:
  devops-network:
    driver: bridge
