

name: Pipeline CI-CD Completo - Evaluacion 2

on:

  push:
  
    branches: [ main, master ]
    
  pull_request:
  
    branches: [ main, master ]



jobs:
  # Análisis estático para la  Segurida
  security_scan:
    name: Escaneo de Seguridad (Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Instalar dependencias del proyecto
        run: npm install

      # Escáner de seguridad
      - name: Analizar vulnerabilidades con Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true 

  # pruebas automatizadas y Cobertura
  test_and_coverage:
    name: Control de Calidad y Pruebas
    needs: [security_scan] 
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4


      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Instalar dependencias del proyecto
        run: npm install

      # aca generamos el reporte para la cobertura (--coverage)
      - name: Ejecutar Pruebas Unitarias con Cobertura
        run: npm test -- --coverage
        continue-on-error: true 

  # Construcción de la solución contenerizada (contenedores)
  build_container:
    name: Compilacion de Imagen Docker
    needs: [test_and_coverage] #no corre si las pruebas de calidad 'quieren' fallar jaja
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4
        

      - name: Construir imagen optimizada (Multi-stage)
        run: docker build -t microservicio-app:latest .

  # Despliegue del Automatizado y Trazabilidad:
  deploy:
  
    name: Despliegue en Entorno Cloud Simulado
    needs: [build_container]
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar Entrega y Despliegue Continuo (CD)
        run: |
          echo "======================================================"
          echo "------------------------------------------------------"
          echo "Iniciando proceso de Despliegue Automático..."
          echo "Verificando consistencia de artefactos..."
          echo "Aplicación desplegada de forma completa y trazable."
          echo "------------------------------------------------------".
          echo "======================================================"
